name: IaC tag and trace

on:
  push:
  pull_request:

env:
  api-key: AKIAIOSFODNN7EXAMAAA
  api-secret: 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 

jobs:
  yor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
